input:
  reviews:
    file_name: All_Beauty
    format: jsonl
    separator: ','
  items:
    file_name: meta_All_Beauty
    format: csv
    separator: ','

output:
  reviews:
    format: csv
    separator: ','
  items:
    format: csv
    separator: ','

noise_profile: rating  # rating | review | combined
kcore: 3
min_rating: 1
min_review_length: 0

split: # if 1.0: no split -- i.e., no data for test, the entire dataset is polluted
  training: 0.8
  test: 0.2
  validation: 0.0
  noise_in_test: false # if true, the noise is injected in the test set as well. If false, the noise is injected only in the training set
  strategy: random holdout # available by default: random holdout | temporal leave-one-out | random leave-one-out



drop_duplicates: true
dataset: amazon_All_Beauty
random_seed: 42
verbose: true








