#profile: human  # bot | human
# human-based operations: # add  -- in this case
# bot-based operations: # remove  | add  | corrupt (if only timestamp corruption is defined)

operation:  add # add | remove | corrupt
timestamp_corruption: false  # set to true to corrupt timestamps and add ratings together

total_budget: 5000 # budget of ratings to add/remove/corrupt

# how the noise is injected:
  # corrupt timestamp uniformly or focused on specific items;
  # add ratings uniformly or focused on top-k popular items, or to top-k users
  # remove ratings uniformly or focused on top-k popular items, or from top-k users
distribution:
  node_selection:
    user_item_ratio: 0.5        # ratio of users vs items to target. 1.0 means only users, 0.0 means only items
    strategy: uniform           # uniform | popularity_based
    popularity_bias: uniform    # uniform | top | least -- only for popularity_based strategy. For example top (least) with target=user means focusing on most (least) active users
    k: 100                      # only for popularity_based strategy. number of nodes (users/items) to focus on. Low k and high budget means hubs creation. K = 100 and user_item_ratio = 0.5 means focusing on top 50 users and top 50 items and add ratings from/to them.
# how many ratings to add/remove per node (user/item)
  per_node_limits:
    max_ratings_per_node: -1  # -1 means no limit
    min_ratings_per_node: 1   # min ratings added per node

structure:
  # only for bot-based operations
  hub_strategy: none           # none | few_hubs | many_hubs
  user_hubs: 0                 # 0 for target: item
  item_hubs: 0                 # 0 for target: user
  hub_concentration: 0.0       # % edges focused on hubs hub in order to have both hubs but also some noise injection on other edges

rating_behavior:
  mean_rating: 3.6             # mean rating of added/removed ratings
  std_rating: 0.7
  min_rating: 1
  max_rating: 5

  value_distribution:
    type: gaussian             # gaussian | uniform | empirical
    clip: true                 # tronca ai limiti min/max

temporal_behavior: # only for timestamp corruption operations
  timestamp_noise: low         # none | low (small random jitters) | high (large perturbation)
  temporal_spread: wide        # wide = ratings spread in large interval, narrow = lot of ratings in short time

constraints:
  avoid_duplicates: true # if true, avoid adding duplicate ratings (same user-item pair) -- true for human-based operations
  preserve_degree_distribution: true # preserve original user/item degree distribution and avoid intentional hubs
  respect_user_activity_profile: true # preserve original user activity distribution
  respect_item_popularity_distribution: true # preserve original item popularity distribution


