# ====== Dataset ======
data_path: '/code/src/baselines/recbole/dataset'
dataset: 'amazon_All_Beauty'   # verr√† sovrascritto dinamicamente se vuoi
benchmark_filename: ['train', 'tune', 'test']
save_model: False
checkpoint_dir: None
load_best_model_at_end: False
load_checkpoint: None
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating

load_col:
  inter: [user_id, item_id, rating]

# ====== Model ======
model: BPR
embedding_size: 64

# ====== Training ======
epochs: 50
train_batch_size: 2048
learning_rate: 0.001
neg_sampling:
  uniform: 1

# ====== Evaluation ======
metrics: ['Recall', 'NDCG']
topk: 10
valid_metric: NDCG@10
eval_args:
  group_by: user
  order: RO
  mode: full
