budget: 10        # total number of reviews to add/remove/corrupt
avoid_duplicates: true    # evita duplicati (stesso user-item pair) se true


# context 1 -- change the review or the rating
random_inconsistencies:
  operation: corrupt
  target: item                       # item | user
  flip: review                    # rating | review. If rating, where the review is positive and the rating is positive, the rating is turned negative -- i.e., from 5 to 1. If review, for a positive rating, we turn the review negative
  selection_strategy: top        # uniform | top | least
  max_reviews_per_node: 10           # max number of reviews modified per node
  min_reviews_per_node: 1            # min number of reviews modified per node
  min_length_of_review: 1            # min number of tokens single space separated
  model: Qwen/Qwen2.5-1.5B-Instruct # TinyLlama/TinyLlama-1.1B-Chat-v1.0
  temporal_behavior:
    start_timestamp: 1009459200     # start of interval (UNIX)
    end_timestamp: 2640995200       # end of interval (UNIX)
  rating_behavior:                  # rating of the added reviews
    min_rating: 1
    max_rating: 5
    sampling_strategy: gaussian      # gaussian | uniform

