budget: 1000 # budget of ratings to add/remove/corrupt
avoid_duplicates: true # if true, avoid adding duplicate ratings (same user-item pair) -- true for human-based operations

timestamp_corruption:
  target: user                        # user | item  -- if user, corrupt timestamps of ratings from selected users; if item, corrupt timestamps of ratings to selected items;
  selection_strategy: top           # uniform | top | least -- random selection of edges
  max_ratings_per_node: 20            # inf means no limit
  min_ratings_per_node: 10             # min ratings added per node
  temporal_behavior:
    corruption_mode: uniform    # uniform | forward | backward
    intensity: medium                 # low | medium | high -- low = days, medium = months, high = years
  rating_behavior:                    # what ratings to corrupt timestamps of
    min_rating: 1
    max_rating: 5
    sampling_strategy: uniform        # uniform | gaussian