quality: true # set to false not to compute quality metrics
cornac:
  models:
    - name: BPR
      params:
        k: 50
        max_iter: 100
        learning_rate: 0.01
        lambda_reg: 0.001
        seed: 42
    - name: LightGCN
      params:
        emb_size: 64
        num_layers: 2
        learning_rate: 0.001
        num_epochs: 100
        lambda_reg: 0.0001
        batch_size: 4096
        seed: 42
        verbose: True
    - name: MostPop
      params: {}



  metrics:
    - NDCG:
        k: 10
    - Recall:
        k: 10
  

custom:



