input:
  reviews:
    file_name: All_Beauty
    format: jsonl
    separator: ','
  items:
    file_name: meta_All_Beauty
    format: csv
    separator: ','

output:
  split: 0.8      # train/test split. this allows you not to include the modified edges in the test vali/set. If 0.0 it will be ignored
  target: cornac
  reviews:
    format: csv
    separator: ','
  items:
    format: csv
    separator: ','

noise_profile: rating  # rating | review | combined
kcore: 5
drop_duplicates: true
dataset: amazon_All_Beauty
random_seed: 42
verbose: true








